version: "3.8"

services:
  api:
    image: ghcr.io/wolfixor/etkala-api:${API_TAG:-latest}
    # env_file: ./api/.env
    env_file: .env
    ports:
      - "8001:8000"
    restart: unless-stopped

  auth:
    image: ghcr.io/wolfixor/etkala-auth:${AUTH_TAG:-latest}
    # env_file: ./auth/.env
    env_file: .env
    ports:
      - "8002:8000"
    restart: unless-stopped

  product:
    image: ghcr.io/wolfixor/etkala-product:${PRODUCT_TAG:-latest}
    # env_file: ./product/.env
    env_file: .env
    ports:
      - "8003:8000"
    restart: unless-stopped

  order:
    image: ghcr.io/wolfixor/etkala-order:${ORDER_TAG:-latest}
    # env_file: ./order/.env
    env_file: .env
    ports:
      - "8004:8000"
    restart: unless-stopped
